# Generated by Django 3.2.16 on 2024-03-30 08:20

import blog.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profanity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'слово',
                'verbose_name_plural': 'Запрещенные слова',
                'ordering': ('word',),
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',), 'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Если установить дату и время в будущем — можно делать отложенные публикации.', validators=[blog.validators.post_pub_date], verbose_name='Дата и время публикации'),
        ),
    ]
